//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnik
    {
        public korisnik()
        {
            this.povijest_test = new HashSet<povijest_test>();
        }
    
        public int id_korisnik { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string email { get; set; }
        public bool administrator { get; set; }
    
        public virtual ICollection<povijest_test> povijest_test { get; set; }
    }
}
