//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class odgovor
    {
        public odgovor()
        {
            this.povijest_odgovor = new HashSet<povijest_odgovor>();
        }
    
        public int id_odgovor { get; set; }
        public string odgovor1 { get; set; }
        public Nullable<int> id_slika { get; set; }
        public int id_pitanja { get; set; }
        public bool tocan { get; set; }
    
        public virtual pitanje pitanje { get; set; }
        public virtual ICollection<povijest_odgovor> povijest_odgovor { get; set; }
        public virtual slika slika { get; set; }
    }
}
