//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class podrucje
    {
        public podrucje()
        {
            this.tema = new HashSet<tema>();
        }
    
        public int id_podrucje { get; set; }
        public string podrucje1 { get; set; }
        public int id_predmet { get; set; }
    
        public virtual predmet predmet { get; set; }
        public virtual ICollection<tema> tema { get; set; }
    }
}
