//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class povijest_test
    {
        public povijest_test()
        {
            this.povijest_pitanje = new HashSet<povijest_pitanje>();
        }
    
        public int id_povijest_test { get; set; }
        public System.DateTime pocetak { get; set; }
        public Nullable<System.DateTime> zavrsetak { get; set; }
        public int id_test { get; set; }
        public int id_korisnik { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual ICollection<povijest_pitanje> povijest_pitanje { get; set; }
        public virtual test test { get; set; }
    }
}
