//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class povijest_odgovor
    {
        public int id_povijest_odgovor { get; set; }
        public int redoslijed_odgovor { get; set; }
        public int id_odgovor { get; set; }
        public int id_povijest_pitanje { get; set; }
        public bool odabran { get; set; }
    
        public virtual odgovor odgovor { get; set; }
        public virtual povijest_pitanje povijest_pitanje { get; set; }
    }
}
