//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class povijest_pitanje
    {
        public povijest_pitanje()
        {
            this.povijest_odgovor = new HashSet<povijest_odgovor>();
        }
    
        public int id_povijest_pitanje { get; set; }
        public int redoslijed_pitanje { get; set; }
        public int id_test_pitanje { get; set; }
        public int id_povijest_test { get; set; }
        public bool rijesen { get; set; }
    
        public virtual ICollection<povijest_odgovor> povijest_odgovor { get; set; }
        public virtual povijest_test povijest_test { get; set; }
        public virtual test_pitanje test_pitanje { get; set; }
    }
}
