//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class predmet
    {
        public predmet()
        {
            this.podrucje = new HashSet<podrucje>();
        }
    
        public int id_predmet { get; set; }
        public string predmet1 { get; set; }
    
        public virtual ICollection<podrucje> podrucje { get; set; }
    }
}
