//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class slika
    {
        public slika()
        {
            this.odgovor = new HashSet<odgovor>();
            this.pitanje = new HashSet<pitanje>();
        }
    
        public int id_slika { get; set; }
        public string slika1 { get; set; }
    
        public virtual ICollection<odgovor> odgovor { get; set; }
        public virtual ICollection<pitanje> pitanje { get; set; }
    }
}
