//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public test()
        {
            this.povijest_test = new HashSet<povijest_test>();
            this.test_pitanje = new HashSet<test_pitanje>();
        }
    
        public int id_test { get; set; }
        public string naziv_test { get; set; }
        public int broj_odgovora { get; set; }
        public int bodovi_tocan { get; set; }
        public int bodovi_netocan { get; set; }
    
        public virtual ICollection<povijest_test> povijest_test { get; set; }
        public virtual ICollection<test_pitanje> test_pitanje { get; set; }
    }
}
