//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPIJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class uputa
    {
        public uputa()
        {
            this.pitanje = new HashSet<pitanje>();
        }
    
        public int id_uputa { get; set; }
        public string uputa1 { get; set; }
        public bool jedan_tocan_odgovor { get; set; }
    
        public virtual ICollection<pitanje> pitanje { get; set; }
    }
}
